-- WESC application database
-- Run this script in Supabase Dashboard -> SQL Editor.
-- It is safe to run more than once.

-- 1. Keep the database name professional. The first version of the project
-- used "regestration" (misspelled), so rename it when it exists.
do $$
begin
  if to_regclass('public.regestration') is not null
     and to_regclass('public.applications') is null then
    alter table public.regestration rename to applications;
  end if;
end
$$;

-- 2. Create the table for new installations.
create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 120),
  email text not null check (char_length(trim(email)) <= 254),
  phone text not null check (char_length(trim(phone)) between 7 and 40),
  course text not null check (char_length(trim(course)) between 2 and 160),
  status text not null default 'new' check (status in ('new', 'contacted', 'enrolled', 'rejected')),
  created_at timestamptz not null default timezone('utc', now())
);

-- 3. Make sure an older table has the fields used by the current form.
alter table public.applications add column if not exists status text not null default 'new';
alter table public.applications add column if not exists created_at timestamptz not null default timezone('utc', now());

-- 4. Turn on Row Level Security. The public browser key cannot bypass this.
alter table public.applications enable row level security;

-- 5. A visitor may submit an application, but anonymous visitors cannot read
-- or edit applications. Staff access should use an authenticated admin role.
drop policy if exists "Public can submit applications" on public.applications;
create policy "Public can submit applications"
on public.applications
for insert
to anon, authenticated
with check (true);

-- Optional staff policy. This works after you add Supabase Auth users.
drop policy if exists "Staff can view applications" on public.applications;
create policy "Staff can view applications"
on public.applications
for select
to authenticated
using (true);

-- 6. Helpful for an admin dashboard later.
create index if not exists applications_created_at_idx
on public.applications (created_at desc);
create index if not exists applications_course_idx
on public.applications (course);
